package mainApp;

enum FitnessMethod {
    ONES, COMPARE_TO_CHROMOSOME, SWITCHES, DECREASING_SIGNIFICANCE, TROUGHS
}

enum SelectionMethod {
    TOP_HALF, ROULETTE, RANK, BEST_RANDOM_WORST, TRUNCATION
}